[package]
name = "fgcd-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
derive_more = "0.99.17"
fgcd-model = { version = "0.1.0", path = "../model" }
spreadsheet-ods = "0.17.0"
